[build]
  command = "yarn build"
  functions = "functions"
  publish = "dist"
[[redirects]]
  from = "/cdk/:page"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/:page"
  to = "/index.html"
  status = 200
